name: TELEChatSRV
version: 1.0
main: com.example.TELEChatSRV.MyPlugin
author: Naufal90
description: Plugin untuk mengirimkan notifikasi server Minecraft ke Telegram.
api-version: 1.19
commands:
  settg:
    description: Mengatur token dan chat ID bot Telegram.
    usage: /settg <token> <chat_id>
    permission: wachat.admin
  reloadtg:
    description: Reload konfigurasi Telegram dari file config.yml.
    usage: /reloadtg
    permission: wachat.admin
permissions:
  wachat.admin:
    description: Memberikan akses untuk mengatur plugin Telegram.
    default: op
