name: WAChatSRV
version: 1.0
main: com.example.WAChatSRV.MyPlugin
api-version: 1.18
commands:
  reloadwasrv:
    description: Muat Ulang Setelan WAChatSRV
    usage: /reloadwasrv
    permission: wasrv.reload
  settcp:
    description: Atur Host dan Port TCP Bot
    usage: /settcp <host> <port>
    permission: wasrv.settcp
permissions:
  wasrv.reload:
    description: Aktifkan Muat Ulang Config
    default: op
  wasrv.settcp:
    description: Aktifkan Pengaturan Host dan Port TCP
    default: op
